name: share_lingo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  mocktail: ^1.0.4
  shimmer: ^3.0.0
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.3
  firebase_crashlytics: ^4.3.5
  geolocator: ^14.0.0
  intl: ^0.19.0
  country_flags: ^3.2.0
  image_picker: ^1.1.0
  firebase_storage: ^12.4.5
  settings_ui: ^2.0.2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  yolo_helper:
    git:
      url: https://github.com/fhelper/flutter-yolo-helper.git
      ref: main
  easy_image_viewer: ^1.5.1

dev_dependencies:
  flutter_native_splash: ^2.3.10
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"  # Square icon for iOS
  adaptive_icon_foreground: "assets/icons/app_icon_rounded.png"  # Rounded icon for Android adaptive icons
  adaptive_icon_background: "#40E0D0"  # Turquoise color
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  color: "#40E0D0"  # Turquoise color
  image: assets/icons/app_icon_rounded.png  # Use rounded icon for splash screen
  android_12:
    image: assets/icons/app_icon_rounded.png
    icon_background_color: "#40E0D0"
    image_dark: assets/icons/app_icon_rounded.png
    icon_background_color_dark: "#40E0D0"
  color_dark: "#40E0D0"
  image_dark: assets/icons/app_icon_rounded.png
  web: false
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
    - assets/icons/
    - assets/images/

