name: share_lingo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  mocktail: ^1.0.4
  shimmer: ^3.0.0
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.3
  firebase_crashlytics: ^4.3.5
  geolocator: ^14.0.0
  intl: ^0.19.0
  country_flags: ^3.2.0
  image_picker: ^1.1.0
  firebase_storage: ^12.4.5
  settings_ui: ^2.0.2
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.3.1
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  flutter_native_splash: ^2.3.10
  yolo_helper:
    git:
      url: https://github.com/fhelper/flutter-yolo-helper.git
      ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
    - assets/icons/
    - assets/images/

