// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDflviY5UlDi8REp2jEKJVbDhTLIqlFMNI',
    appId: '1:497492641943:web:9c7d456662a6292b4e81d2',
    messagingSenderId: '497492641943',
    projectId: 'share-lingo-app',
    authDomain: 'share-lingo-app.firebaseapp.com',
    storageBucket: 'share-lingo-app.firebasestorage.app',
    measurementId: 'G-BEECQ8L4H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApuXxpOi27Fg6J2WD1EVXdwGczRnq0RGs',
    appId: '1:497492641943:android:8c7096ca2a3dbc424e81d2',
    messagingSenderId: '497492641943',
    projectId: 'share-lingo-app',
    storageBucket: 'share-lingo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJpxJ3j6xkBTD6uEiXRm3U41eMgEykwyg',
    appId: '1:497492641943:ios:de49b5467cfbc17b4e81d2',
    messagingSenderId: '497492641943',
    projectId: 'share-lingo-app',
    storageBucket: 'share-lingo-app.firebasestorage.app',
    iosBundleId: 'com.example.shareLingo',
  );
}
